FROM node:20-alpine AS base

RUN apk add --no-cache git bash

WORKDIR /app
RUN git clone https://github.com/IntersectMBO/govtool.git /app


WORKDIR /app/govtool/frontend
# RUN yarn install

COPY start-govtool.sh /usr/local/bin/start-govtool.sh
RUN chmod +x /usr/local/bin/start-govtool.sh

EXPOSE 5173

ENTRYPOINT ["/usr/local/bin/start-govtool.sh"]