apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ $.Chart.Name }}"
  namespace: {{ .Values.namespace }}
  labels:
    app: "{{ $.Chart.Name }}"
    service: "{{ $.Chart.Name }}"
spec:
  selector:
    matchLabels:
      app: "{{ $.Chart.Name }}"
      service: "{{ $.Chart.Name }}"
  replicas: {{ .Values.image.backend.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: "{{ $.Chart.Name }}"
        service: "{{ $.Chart.Name }}"
    spec:
      imagePullSecrets:
        - name: {{ .Values.image.backend.pullSecret }}
      containers:
      - name: app
        image: "{{ .Values.image.backend.repository }}:{{ .Values.image.backend.tag }}"
        imagePullPolicy: {{ .Values.image.backend.pullPolicy }}
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 1
          periodSeconds: 10
        resources:
          limits:
            memory: 8192Mi
            cpu: 1
          requests:
            cpu: 50m
            memory: 256Mi
        envFrom:
          - secretRef:
              name: "{{ $.Chart.Name }}-secrets"
        ports:
          - name: node
            containerPort: 3000
            protocol: TCP
        volumeMounts:
          - name: node-ipc
            mountPath: /ipc
            readOnly: false
      - name: ipc
        image: alpine/socat:1.8.0.0
        env:
        - name: CARDANO_NODE_SOCKET_TCP_HOST
          value: "{{ index .Values.cardano_node 0 "tcp_host" }}"
        - name: CARDANO_NODE_SOCKET_TCP_PORT
          value: "{{ index .Values.cardano_node 0 "tcp_port" }}"
        - name: SOCAT_TIMEOUT
          value: "3600"
        command: [
            "sh",
            "-c",
            "socat UNIX-LISTEN:/ipc/node.socket,fork TCP:${CARDANO_NODE_SOCKET_TCP_HOST}:${CARDANO_NODE_SOCKET_TCP_PORT},ignoreeof"
        ]
        volumeMounts:
        - mountPath: /ipc
          name: node-ipc
          readOnly: false
      volumes:
        - name: node-ipc
          emptyDir: {}
